- name: Удаление стенда debian 11
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/home/alex/myStorage/storage_for_VMs"
    vm_name: stand
    ipaddr: 192.168.122.100
  tasks:
    - name: Undefine виртуальной машины
      community.libvirt.virt:
        command: undefine
        name: "{{ vm_name }}"
      register: vm_result

    - name: Destroy виртуальной машины
      community.libvirt.virt:
        command: destroy
        name: "{{ vm_name }}"
      register: vm_result

    - name: Удаление диска виртуальной машины
      ansible.builtin.file:
        path: "{{pool_dir}}/{{ vm_name }}.qcow2"
        state: absent
    
    - name: Удаляем запись из /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ipaddr }} {{ vm_name }}"
        state: absent

    - name: Удаляем запись из known_hosts
      become: false
      ansible.builtin.replace:
        path: ~/.ssh/known_hosts
        regexp: "{{ vm_name }}\\s.+\\sssh-(rsa)\\s.+\\n\\S.+\\n\\S.+"
        replace: ""

    - name: Вывод результата
      debug:
        msg: "Виртуальная машина удалена"
